import PublicPageLayout from '../components/PublicPageLayout'
import { Link } from 'react-router-dom'

const SECTIONS = [
  {
    icon: 'gavel',
    title: '1. Acceptance of Terms',
    body: 'By accessing or using MedaGen ("the Service"), you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree, you must not use the Service. We may update these Terms at any time; continued use after the effective date constitutes acceptance of the updated Terms.',
  },
  {
    icon: 'health_and_safety',
    title: '2. Nature of the Service',
    body: 'MedaGen is an AI-assisted skin analysis tool designed to provide informational guidance only. The Service is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the guidance of a qualified healthcare provider with any questions you may have regarding a medical condition.',
  },
  {
    icon: 'warning',
    title: '3. Medical Disclaimer',
    body: 'The results and information provided by MedaGen are generated by machine learning models and are probabilistic in nature. They may be inaccurate, incomplete, or inapplicable to your specific situation. MedaGen does not provide medical diagnoses. Never disregard professional medical advice or delay seeking it because of something you have read on MedaGen.',
  },
  {
    icon: 'person',
    title: '4. User Responsibilities',
    body: 'You agree to (a) provide accurate information when creating your account and health profile; (b) use the Service only for lawful purposes; (c) not attempt to reverse-engineer, scrape, or circumvent any security measure; (d) not upload images of minors for analysis without parental consent; (e) keep your login credentials confidential and notify us immediately of any unauthorised access.',
  },
  {
    icon: 'verified',
    title: '5. Account Eligibility',
    body: 'You must be at least 13 years of age to create an account. If you are under 18, you confirm that you have obtained parental or guardian consent. MedaGen reserves the right to suspend or terminate accounts that violate these Terms.',
  },
  {
    icon: 'copyright',
    title: '6. Intellectual Property',
    body: 'All content, trademarks, AI models, software, and technology associated with MedaGen are the exclusive property of MedaGen AI Technologies or its licensors. You are granted a limited, non-exclusive, non-transferable licence to use the Service for personal, non-commercial purposes. You retain ownership of the images you upload; by uploading, you grant us a limited licence to process them for the purpose of delivering the Service.',
  },
  {
    icon: 'block',
    title: '7. Prohibited Uses',
    body: 'You may not use the Service to (a) submit false or misleading health information; (b) impersonate any person or entity; (c) conduct automated scraping or data harvesting; (d) interfere with or disrupt the integrity of the Service; (e) use the Service for commercial telemedicine purposes without a separate enterprise agreement.',
  },
  {
    icon: 'money_off',
    title: '8. Payment & Subscriptions',
    body: 'Free tier users have access to a limited number of analyses per month. Paid plans are billed monthly or annually in advance. All fees are non-refundable except where required by applicable law. We reserve the right to change pricing with 30 days\' notice to existing subscribers.',
  },
  {
    icon: 'shield',
    title: '9. Limitation of Liability',
    body: 'To the maximum extent permitted by law, MedaGen AI Technologies shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including any medical decisions made based on AI-generated results. Our total liability to you shall not exceed the amount paid by you to MedaGen in the 12 months preceding the claim.',
  },
  {
    icon: 'cancel',
    title: '10. Termination',
    body: 'Either party may terminate these Terms at any time. You may terminate by deleting your account. We may terminate or suspend your access immediately, without prior notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties. Upon termination, your right to use the Service ceases immediately.',
  },
  {
    icon: 'public',
    title: '11. Governing Law',
    body: 'These Terms are governed by the laws of Vietnam without regard to its conflict-of-law provisions. Any dispute arising from these Terms shall be resolved in the courts of Ho Chi Minh City, Vietnam.',
  },
]

export default function TermsOfServicePage() {
  return (
    <PublicPageLayout>
      {/* Hero */}
      <div className="bg-gradient-to-br from-slate-800 to-slate-900 py-16 px-4 relative overflow-hidden">
        <div className="absolute inset-0 opacity-5 pointer-events-none">
          <div className="absolute top-0 right-0 w-96 h-96 rounded-full bg-primary translate-x-32 -translate-y-32" />
        </div>
        <div className="relative max-w-3xl mx-auto text-center">
          <p className="text-slate-400 text-xs font-bold uppercase tracking-widest mb-3">Legal</p>
          <h1 className="text-4xl md:text-5xl font-black text-white mb-4">Terms of Service</h1>
          <p className="text-slate-400 text-base max-w-xl mx-auto">Last updated: January 1, 2025. Please read these terms carefully before using MedaGen.</p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-4 py-14 space-y-10">
        {/* Medical disclaimer box */}
        <div className="flex gap-4 p-6 rounded-2xl border border-amber-200 dark:border-amber-900/40 bg-amber-50 dark:bg-amber-950/20">
          <span className="material-symbols-outlined text-amber-500 text-2xl shrink-0 mt-0.5">medical_information</span>
          <div>
            <p className="font-bold text-sm text-amber-800 dark:text-amber-300 mb-1">Important Medical Disclaimer</p>
            <p className="text-xs text-amber-700 dark:text-amber-400 leading-relaxed">
              MedaGen is an informational tool only. It is not a medical device, does not provide diagnoses, and is not a substitute for professional medical care. Always consult a qualified healthcare provider.
            </p>
          </div>
        </div>

        {SECTIONS.map((section) => (
          <section key={section.title} className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="size-9 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                <span className="material-symbols-outlined text-primary text-base">{section.icon}</span>
              </div>
              <h2 className="text-base font-bold text-slate-900 dark:text-white">{section.title}</h2>
            </div>
            <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">{section.body}</p>
          </section>
        ))}

        {/* Contact block */}
        <div className="text-center pt-4">
          <p className="text-sm text-slate-500 dark:text-slate-400 mb-3">
            Questions about these terms?{' '}
            <Link to="/contact" className="text-primary font-semibold hover:underline">Contact us</Link>
            {' '}or email{' '}
            <a href="mailto:legal@medagen.ai" className="text-primary font-semibold hover:underline">legal@medagen.ai</a>
          </p>
          <p className="text-xs text-slate-400">MedaGen AI Technologies · Ho Chi Minh City, Vietnam</p>
        </div>
      </div>
    </PublicPageLayout>
  )
}
