name: Deploy Backend to Hugging Face Space

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_URL: "https://huggingface.co/spaces/Cuong2004/Medagen_EXE"
        run: |
          git config --global credential.helper store
          echo "https://user:$HF_TOKEN@huggingface.co" > ~/.git-credentials
          git clone $SPACE_URL hf_space
          cp -r backend/* hf_space/
          cd hf_space
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Auto deploy backend from GitHub Actions" || true
          git push origin main
